apiVersion: v1
kind: Pod

metadata:
  name: database-pod

spec:
  tolerations:
  - key: workload
    operator: Equal
    value: database
    effect: NoSchedule

  containers:
  - name: nginx
    image: nginx
