apiVersion: v1
kind: Pod

metadata:
  name: startup-demo

spec:
  containers:
  - name: app
    image: busybox

    command:
    - sh
    - -c
    - |
      echo "Application is starting..."
      sleep 30

      echo "app-ready" > /tmp/healthy
      echo "Application is now ready."

      sleep 3600

    startupProbe:
      exec:
        command:
        - cat
        - /tmp/healthy

      periodSeconds: 5
      failureThreshold: 12
